Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import cvxpy as cp
from gurobipy import *

# Define the problem data
n = 2

# Define the decision variables
x = cp.Variable(n)

# Define the first level objective function and constraint
f1 = cp.sum_squares(x)
g = x[0] + x[1] - 1

# Define the second level objective function and constraint
f2 = cp.norm(x - [1, 0], 2)
h = x[0] - x[1] - 1

# Define the hierarchy
hierarchy = [f1, f2]

# Define the constraints
constraints = [g <= 0, h <= 0]

# Solve the problem using CVXPY and Gurobi
prob = cp.hierarchy_problem(hierarchy, constraints)
prob.solve(solver=cp.GUROBI)

# Print the optimal value and the optimal solution for each level
for i, level in enumerate(prob.levels):
    print("Level", i+1)
    print("Optimal value =", level.value)
    print("Optimal solution =", level.variables()[0].value)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[9], line 25[0m
[1;32m     22[0m constraints [38;5;241m=[39m [g [38;5;241m<[39m[38;5;241m=[39m [38;5;241m0[39m, h [38;5;241m<[39m[38;5;241m=[39m [38;5;241m0[39m]
[1;32m     24[0m [38;5;66;03m# Solve the problem using CVXPY and Gurobi[39;00m
[0;32m---> 25[0m prob [38;5;241m=[39m [43mcp[49m[38;5;241;43m.[39;49m[43mhierarchy_problem[49m(hierarchy, constraints)
[1;32m     26[0m prob[38;5;241m.[39msolve(solver[38;5;241m=[39mcp[38;5;241m.[39mGUROBI)
[1;32m     28[0m [38;5;66;03m# Print the optimal value and the optimal solution for each level[39;00m

[0;31mAttributeError[0m: module 'cvxpy' has no attribute 'hierarchy_problem'
AttributeError: module 'cvxpy' has no attribute 'hierarchy_problem'

